apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: student-portal
type: Opaque
stringData:
  db_link: postgresql://myadmin:Admin123@student-portal.cvik8accw2tk.ap-south-1.rds.amazonaws.com:5432/postgres