apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-config
  namespace: craftista
data:
  application.properties: |
    # Catalogue Service Endpoint
    catalogue.service-url=http://catalogue:5000/api/products

    # H2
    spring.h2.console.enabled=true
    spring.h2.console.path=/h2-console

    # Datasource
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driver-class-name=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=password

    # JPA
    spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: craftista
  labels:
    app: voting
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      labels:
        app: voting
        tier: backend
    spec:
      containers:
      - name: voting
        image: 879381241087.dkr.ecr.ap-south-1.amazonaws.com/prod-craftica-voting:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /app/application.properties
          subPath: application.properties
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1200m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/origamis
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/origamis
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: voting-config
---
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: craftista
  labels:
    app: voting
spec:
  type: ClusterIP
  selector:
    app: voting
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
