apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: student-portal
type: Opaque
stringData:
  db_link: postgresql://myadmin:mypassword@student-portal.cizic4iqc955.us-east-1.rds.amazonaws.com:5432/postgres
  