name: Class31-3tier-Build

on:
  # push:
  #   branches:
  #     - main

#   # run only if some file in 'src' folder was changed
# - if: steps.changes.outputs.src == 'true'
#   run: ...

  push:
    branches:
      - main
    paths:
      - 'class30-31-k8s-tf-3-tier-app/**'

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  frontend_repo: devopsdojo-frontend
  IMAGE_TAG: ${{ github.sha }}
  PATH_TO_BUILD: ./class30-31-k8s-tf-3-tier-app

jobs:
  backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ECR_REPOSITORY: devopsdojo-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::307946636515:role/eks-github-actions-build-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Building the Docker image... ${{ steps.login-ecr.outputs.registry }}"
          cd ${{ env.PATH_TO_BUILD }}/application/backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


  frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ECR_REPOSITORY: devopsdojo-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::307946636515:role/eks-github-actions-build-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Building the Docker image... ${{ steps.login-ecr.outputs.registry }}"
          cd ${{ env.PATH_TO_BUILD }}/application/frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
